In [374]:
import pandas
import numpy

In [375]:
data = pandas.read_csv("heart1.csv")
df = pandas.DataFrame(data)
df

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40   M           ATA        140          289          0     Normal   
1     49   F           NAP        160          180          0     Normal   
2     37   M           ATA        130          283          0         ST   
3     48   F           ASY        138          214          0     Normal   
4     54   M           NAP        150          195          0     Normal   
..   ...  ..           ...        ...          ...        ...        ...   
913   45   M            TA        110          264          0     Normal   
914   68   M           ASY        144          193          1     Normal   
915   57   M           ASY        130          131          0     Normal   
916   57   F           ATA        130          236          0        LVH   
917   38   M           NAP        138          175          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0      172              N      0.0       Up             0  
1      156              N      1.0     Flat             1  
2       98              N      0.0       Up             0  
3      108              Y      1.5     Flat             1  
4      122              N      0.0       Up             0  
..     ...            ...      ...      ...           ...  
913    132              N      1.2     Flat             1  
914    141              N      3.4     Flat             1  
915    115              Y      1.2     Flat             1  
916    174              N      0.0     Flat             1  
917    173              N      0.0       Up             0  

[918 rows x 12 columns]

In [376]:
# target >>> HeartDisease
# input features >>> Age	Sex	ChestPainType	RestingBP	Cholesterol	FastingBS	RestingECG	MaxHR	ExerciseAngina	Oldpeak	ST_Slope

In [377]:
df = df.drop(columns=['Age','Sex'],axis=1)    # df = ... or inplace = True for change in data frame
df

ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0             ATA        140          289          0     Normal    172   
1             NAP        160          180          0     Normal    156   
2             ATA        130          283          0         ST     98   
3             ASY        138          214          0     Normal    108   
4             NAP        150          195          0     Normal    122   
..            ...        ...          ...        ...        ...    ...   
913            TA        110          264          0     Normal    132   
914           ASY        144          193          1     Normal    141   
915           ASY        130          131          0     Normal    115   
916           ATA        130          236          0        LVH    174   
917           NAP        138          175          0     Normal    173   

    ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0                N      0.0       Up             0  
1                N      1.0     Flat             1  
2                N      0.0       Up             0  
3                Y      1.5     Flat             1  
4                N      0.0       Up             0  
..             ...      ...      ...           ...  
913              N      1.2     Flat             1  
914              N      3.4     Flat             1  
915              Y      1.2     Flat             1  
916              N      0.0     Flat             1  
917              N      0.0       Up             0  

[918 rows x 10 columns]

In [378]:
df.isna().sum()    # no missing values

ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [379]:
# check any object present and if present convert to numerical - encoding
# encoding >>>> convert to appropriate integer value

from sklearn.preprocessing import LabelEncoder      # ML concept in sklearn

le = LabelEncoder()

df['ChestPainType'] = le.fit_transform(df['ChestPainType'])   # fit >> collect   , transform >> transform  or fit_transform
df['RestingECG'] = le.fit_transform(df['RestingECG'])
df['ExerciseAngina'] = le.fit_transform(df['ExerciseAngina'])
df['ST_Slope'] = le.fit_transform(df['ST_Slope'])
df



ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  MaxHR  \
0                1        140          289          0           1    172   
1                2        160          180          0           1    156   
2                1        130          283          0           2     98   
3                0        138          214          0           1    108   
4                2        150          195          0           1    122   
..             ...        ...          ...        ...         ...    ...   
913              3        110          264          0           1    132   
914              0        144          193          1           1    141   
915              0        130          131          0           1    115   
916              1        130          236          0           0    174   
917              2        138          175          0           1    173   

     ExerciseAngina  Oldpeak  ST_Slope  HeartDisease  
0                 0      0.0         2             0  
1                 0      1.0         1             1  
2                 0      0.0         2             0  
3                 1      1.5         1             1  
4                 0      0.0         2             0  
..              ...      ...       ...           ...  
913               0      1.2         1             1  
914               0      3.4         1             1  
915               1      1.2         1             1  
916               0      0.0         1             1  
917               0      0.0         2             0  

[918 rows x 10 columns]

In [380]:
X = df.iloc[:,:-1] # input features
Y =df.iloc[:,-1]   # ouput / result


In [381]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size= 0.3)

In [382]:
X_train

ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  MaxHR  \
197              1        150          268          0           1    136   
42               1        150          264          0           1    168   
24               2        130          215          0           1    138   
354              0        120            0          0           2     92   
345              0        135            0          0           1    130   
..             ...        ...          ...        ...         ...    ...   
694              1        120          236          0           1    178   
186              1        130          251          0           1    110   
766              2        120          219          0           1    158   
235              1        120          200          0           1    160   
595              0        130          186          1           0    140   

     ExerciseAngina  Oldpeak  ST_Slope  
197               0      0.0         2  
42                0      0.0         2  
24                0      0.0         2  
354               0      0.3         2  
345               0      0.0         1  
..              ...      ...       ...  
694               0      0.8         2  
186               0      0.0         2  
766               0      1.6         1  
235               1      1.0         1  
595               1      0.5         1  

[642 rows x 9 columns]

In [383]:
X_test

ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  MaxHR  \
647              2        120          215          0           1    170   
302              0        125            0          1           1    120   
517              0        150          235          0           1    120   
72               0        120          182          0           1    150   
830              1        130          204          0           0    172   
..             ...        ...          ...        ...         ...    ...   
651              0        140          207          0           0    138   
125              1        120          246          0           1    110   
162              1        160          263          0           1    174   
521              0        120          282          0           2    135   
828              0        128          216          0           0    131   

     ExerciseAngina  Oldpeak  ST_Slope  
647               0      0.0         2  
302               0      1.5         2  
517               1      1.5         1  
72                0      0.0         1  
830               0      1.4         2  
..              ...      ...       ...  
651               1      1.9         2  
125               0      0.0         2  
162               0      0.0         2  
521               1      4.0         0  
828               1      2.2         1  

[276 rows x 9 columns]

In [384]:
# only x need to scale , y no need to scale having only 1 column

from sklearn.preprocessing import StandardScaler # Z = (x-mean)/std

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)    # model need to be predict the result for the unseen data - Data leakage



In [385]:
X_train

array([[ 2.37570560e-01,  9.82642085e-01,  6.05927793e-01, ...,
        -8.11735627e-01, -8.24083931e-01,  1.05488555e+00],
       [ 2.37570560e-01,  9.82642085e-01,  5.70256383e-01, ...,
        -8.11735627e-01, -8.24083931e-01,  1.05488555e+00],
       [ 1.28943470e+00, -9.37206835e-02,  1.33281611e-01, ...,
        -8.11735627e-01, -8.24083931e-01,  1.05488555e+00],
       ...,
       [ 1.28943470e+00, -6.31902068e-01,  1.68953021e-01, ...,
        -8.11735627e-01,  7.13886661e-01, -5.88892421e-01],
       [ 2.37570560e-01, -6.31902068e-01, -4.86175758e-04, ...,
         1.23192819e+00,  1.37147689e-01, -5.88892421e-01],
       [-8.14293576e-01, -9.37206835e-02, -1.25336110e-01, ...,
         1.23192819e+00, -3.43468121e-01, -5.88892421e-01]],
      shape=(642, 9))

In [386]:
# Data preprocessing steps:
# ========================

# missing values handle
# outliers
# data transform
# scaling
# data reduction

In [387]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()

model = knn.fit(X_train,Y_train)

y_pred = model.predict(X_test)

y_pred

array([0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1])

In [388]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_pred,Y_test))

0.8659420289855072


In [389]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(Y_test,y_pred)

cm

array([[106,  17],
       [ 20, 133]])

In [391]:
#iloc for accessing the index if data frame is not labelled

d = {"name": ["a","b","c"],
     "age" : [2,3,4]}

df1 = pandas.DataFrame(d,index=["r1","r2","r3"])
df1

name  age
r1    a    2
r2    b    3
r3    c    4