create a 4*4 matrix

display the last column
display the first 2 row
sum of first two rows
avg of last two columns
max and min of 3rd column

In [ ]:
import numpy

In [ ]:
numbers = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
m = numpy.array(numbers)
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
print(m[:,-1]) # display the last column
print(m[0:2])  # display the first 2 row
add = m[0:2]
print(add.sum())  # sum of first two rows
average = m[:,3::]
print(average.mean()) # avg of last two columns
third = m[:,2]
print(third.max())  # max and min of 3rd column
print(third.min())

[ 4  8 12 16]
[[1 2 3 4]
 [5 6 7 8]]
36
10.0
15
3


given a list of numbers to create a new list that contains only the even numbers from the original list but if an even numbers is greater than 10, it should be replaced with the string "BIG".

numbers = [1,4,12,5,8,15,20,3]      # [4,'BIG',8,'BIG']

In [ ]:
numbers = [1,4,12,5,8,15,20,3] 
even = []
for i in numbers:

    if i % 2 == 0:
        if i > 10:
            even.append('BIG')
        else:
            even.append(i)
print(even)




[4, 'BIG', 8, 'BIG']


In [ ]:

numbers = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
n = numpy.array(numbers)

# filter the elements which are greater than 10
print(n[n > 10])

# find the odd numbers
print(n[n % 2 != 0])

# find the odd numbers in first column
print(n[0][n[0] % 2 != 0])

# find the sum of odd numbers in first column
print(n[0][n[0] % 2 != 0].sum())


[11 12 13 14 15 16]
[ 1  3  5  7  9 11 13 15]
[1 3]
4


In [ ]:
# create 3 * 4 matrix
# random module contain randint used to pick random numbers between low and high
n = numpy.random.randint(1,50,size=(3,4))   # low,high,size
n

array([[17, 41, 44, 15],
       [10, 28,  7, 24],
       [41, 35,  2, 28]], dtype=int32)

In [ ]:
# create an array of numbers from 1 to 10
n =numpy.arange(1,11)   # used to generate sequence of numbers from start to stop
n

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Types of matrix
===============

zero matrix
one matrix
identity matrix
square matrix

In [ ]:
n = numpy.zeros((3,4),dtype=int) # contains all elements as 0
print(n)
m = numpy.ones((3,2),dtype=int) # contains all elements as 1
print(m)
# number of column equals to number of rows is defined as square matrix
s = numpy.identity(4) # 4 * 4 matrix with diagonal as 1 
print(s)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1]
 [1 1]
 [1 1]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
n = numpy.random.randint(1,25,size=(4,3))
print(n)

[[19 16  1]
 [ 1 21 13]
 [ 4 12  2]
 [10  8 12]]


In [ ]:
# n[1,-1]  get the value 8
n[1,-1] = 16 # here value 8 replaced by  16
n


array([[19, 16,  1],
       [ 1, 21, 16],
       [ 4, 12,  2],
       [10,  8, 12]], dtype=int32)

In [ ]:
n[1] = 16 # all elements of row 1 to 16
n

array([[19, 16,  1],
       [16, 16, 16],
       [ 4, 12,  2],
       [10,  8, 12]], dtype=int32)

In [ ]:
# to get the row sum 
a = numpy.sum(n,axis = 1)
b = numpy.sum(n,axis = 0)   # column
print(a)
print(b)
print(n)

[36 48 18 30]
[49 52 31]
[[19 16  1]
 [16 16 16]
 [ 4 12  2]
 [10  8 12]]


In [ ]:
# arithmetic operation

n1 = numpy.random.randint(1,60,size=(4,3))
n1

array([[24, 17, 59],
       [15, 30, 59],
       [58, 47, 57],
       [20, 43, 23]], dtype=int32)

In [ ]:
n1 = n1 + 10  # vectorized 
print(n1)

numpy.add(n,n1)  # sum of two array


[[44 37 79]
 [35 50 79]
 [78 67 77]
 [40 63 43]]


array([[63, 53, 80],
       [51, 66, 95],
       [82, 79, 79],
       [50, 71, 55]], dtype=int32)

In [ ]:
print(numpy.sqrt(n1))   # square root of all elements
print(numpy.mean(n1))   # avg of whole array
print(numpy.std(n1))    # standard deviation of array

[[6.63324958 6.08276253 8.88819442]
 [5.91607978 7.07106781 8.88819442]
 [8.83176087 8.18535277 8.77496439]
 [6.32455532 7.93725393 6.55743852]]
57.666666666666664
17.143187827498387


In [ ]:
# find the sqrt of elements in the first row
print(numpy.sqrt(n1[0]))

# find the mean of elements in the first two rows
print(numpy.mean(n[0:2]))


[6.63324958 6.08276253 8.88819442]
14.0


In [ ]:
n2 = numpy.random.randint(1,60,size=(4,3))
n2
# filter even numbers and greater than 30
print(n2[(n2 % 2 == 0) & (n2>30)])
# filter odd numbers and greater than 25
print(n1[(n1 % 2 != 0) | (n1 > 25)])

[40 36 50]
[52 39 38 41 19 32 47 17 11 48]


In [ ]:
n3 = numpy.random.randint(10,25,size=(4,4))
n3


array([[11, 17, 15, 11],
       [13, 11, 13, 14],
       [12, 14, 18, 16],
       [23, 24, 21, 14]], dtype=int32)

In [ ]:
a = numpy.sum(n3,axis = 1)
b = numpy.sum(n3,axis = 0)
print(a)
print(b)

[54 51 60 82]
[59 66 67 55]


In [ ]:
n3[(n3 > 18) & (n3 < 23)] 

array([21], dtype=int32)

In [ ]:
n3[(n3 > 20)] = 0
n3

array([[11, 17, 15, 11],
       [13, 11, 13, 14],
       [12, 14, 18, 16],
       [ 0,  0,  0, 14]], dtype=int32)

In [ ]:
n3[(n3 % 2 != 0) | (n3 % 5 == 0)]

array([11, 17, 15, 11, 13, 11, 13,  0,  0,  0], dtype=int32)

In [ ]:
numpy.sum(n3[2::])

np.int64(74)

In [ ]:
n3[:,1:3]

array([[17, 15],
       [11, 13],
       [14, 18],
       [ 0,  0]], dtype=int32)

In [ ]:
n3 + numpy.mean(n3)

array([[22.1875, 28.1875, 26.1875, 22.1875],
       [24.1875, 22.1875, 24.1875, 25.1875],
       [23.1875, 25.1875, 29.1875, 27.1875],
       [11.1875, 11.1875, 11.1875, 25.1875]])