In [2]:
print("hello world!")

hello world!


what is numpy
use of numerical values in data science
difference between array and list
advantage of ipynb

In [ ]:
import numpy

create an array of elements from 1 to 10

In [2]:
numbers = list(range(1,11))
result = numpy.array(numbers)
result

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

create an array of odd numbers from 1 to n , n should be entered by user

In [6]:
n = int(input("enter the limit :"))
numbers = list(range(1,n+1,2))
result = numpy.array(numbers)
result

array([1, 3, 5, 7, 9])

Types of array
=============

one_dimensional  >>  x  >>>>>>>>>>>>    [1,2,3,4]

two_dimensional  >>  x,y >>>>>>>>>>>    [[1,2,3,4],[5,6,7,8]]

three_dimensional >> z,x,y >>>>>>>>>    [[[1,2,3,4],[5,6,7,8]] , [[1,2,3,4],[5,6,7,8]]]

In [9]:
numbers = [[1,2,3,4],[5,6,7,8]]
result = numpy.array(numbers)
result
result.shape

(2, 4)

create a 2d array of 4 rows and 3 columns

In [10]:
numbers = [[1,2,3],[5,6,7],[3,4,5],[8,6,9]]
result = numpy.array(numbers)
result

array([[1, 2, 3],
       [5, 6, 7],
       [3, 4, 5],
       [8, 6, 9]])