In [36]:
import pandas
import numpy

In [37]:
data = pandas.read_csv('health_lifestyle_dataset.csv')
df = pandas.DataFrame(data)
df

id  age  gender   bmi  daily_steps  sleep_hours  water_intake_l  \
0           1   56    Male  20.5         4198          3.9             3.4   
1           2   69  Female  33.3        14359          9.0             4.7   
2           3   46    Male  31.6         1817          6.6             4.2   
3           4   32  Female  38.2        15772          3.6             2.0   
4           5   60  Female  33.6         6037          3.8             4.0   
...       ...  ...     ...   ...          ...          ...             ...   
99995   99996   53    Male  33.1         4726          3.9             2.0   
99996   99997   22    Male  35.1        11554          4.5             3.1   
99997   99998   37    Male  18.9         3924          3.8             1.0   
99998   99999   72  Female  27.8        16110          5.6             0.8   
99999  100000   37    Male  35.4         8222          9.1             1.8   

       calories_consumed  smoker  alcohol  resting_hr  systolic_bp  \
0                   1602       0        0          97          161   
1                   2346       0        1          68          116   
2                   1643       0        1          90          123   
3                   2460       0        0          71          165   
4                   3756       0        1          98          139   
...                  ...     ...      ...         ...          ...   
99995               3118       0        1          56          105   
99996               1967       0        0          51          149   
99997               2328       0        0          69           92   
99998               3093       0        0          93          164   
99999               3942       0        1          71          145   

       diastolic_bp  cholesterol  family_history  disease_risk  
0               111          240               0             0  
1                65          207               0             0  
2                99          296               0             0  
3                95          175               0             0  
4                61          294               0             0  
...             ...          ...             ...           ...  
99995            76          282               0             0  
99996            77          192               0             0  
99997           117          218               0             0  
99998            72          188               0             0  
99999            80          276               0             1  

[100000 rows x 16 columns]

In [38]:
# target >>>>>>>>>> disease_risk
# input features >>> remaining

In [39]:
df = df.drop('id',axis = 1)
df

age  gender   bmi  daily_steps  sleep_hours  water_intake_l  \
0       56    Male  20.5         4198          3.9             3.4   
1       69  Female  33.3        14359          9.0             4.7   
2       46    Male  31.6         1817          6.6             4.2   
3       32  Female  38.2        15772          3.6             2.0   
4       60  Female  33.6         6037          3.8             4.0   
...    ...     ...   ...          ...          ...             ...   
99995   53    Male  33.1         4726          3.9             2.0   
99996   22    Male  35.1        11554          4.5             3.1   
99997   37    Male  18.9         3924          3.8             1.0   
99998   72  Female  27.8        16110          5.6             0.8   
99999   37    Male  35.4         8222          9.1             1.8   

       calories_consumed  smoker  alcohol  resting_hr  systolic_bp  \
0                   1602       0        0          97          161   
1                   2346       0        1          68          116   
2                   1643       0        1          90          123   
3                   2460       0        0          71          165   
4                   3756       0        1          98          139   
...                  ...     ...      ...         ...          ...   
99995               3118       0        1          56          105   
99996               1967       0        0          51          149   
99997               2328       0        0          69           92   
99998               3093       0        0          93          164   
99999               3942       0        1          71          145   

       diastolic_bp  cholesterol  family_history  disease_risk  
0               111          240               0             0  
1                65          207               0             0  
2                99          296               0             0  
3                95          175               0             0  
4                61          294               0             0  
...             ...          ...             ...           ...  
99995            76          282               0             0  
99996            77          192               0             0  
99997           117          218               0             0  
99998            72          188               0             0  
99999            80          276               0             1  

[100000 rows x 15 columns]

In [40]:
df = df.drop('age',axis = 1)
df

gender   bmi  daily_steps  sleep_hours  water_intake_l  \
0        Male  20.5         4198          3.9             3.4   
1      Female  33.3        14359          9.0             4.7   
2        Male  31.6         1817          6.6             4.2   
3      Female  38.2        15772          3.6             2.0   
4      Female  33.6         6037          3.8             4.0   
...       ...   ...          ...          ...             ...   
99995    Male  33.1         4726          3.9             2.0   
99996    Male  35.1        11554          4.5             3.1   
99997    Male  18.9         3924          3.8             1.0   
99998  Female  27.8        16110          5.6             0.8   
99999    Male  35.4         8222          9.1             1.8   

       calories_consumed  smoker  alcohol  resting_hr  systolic_bp  \
0                   1602       0        0          97          161   
1                   2346       0        1          68          116   
2                   1643       0        1          90          123   
3                   2460       0        0          71          165   
4                   3756       0        1          98          139   
...                  ...     ...      ...         ...          ...   
99995               3118       0        1          56          105   
99996               1967       0        0          51          149   
99997               2328       0        0          69           92   
99998               3093       0        0          93          164   
99999               3942       0        1          71          145   

       diastolic_bp  cholesterol  family_history  disease_risk  
0               111          240               0             0  
1                65          207               0             0  
2                99          296               0             0  
3                95          175               0             0  
4                61          294               0             0  
...             ...          ...             ...           ...  
99995            76          282               0             0  
99996            77          192               0             0  
99997           117          218               0             0  
99998            72          188               0             0  
99999            80          276               0             1  

[100000 rows x 14 columns]

In [41]:
df = df.drop('gender',axis = 1)
df

bmi  daily_steps  sleep_hours  water_intake_l  calories_consumed  \
0      20.5         4198          3.9             3.4               1602   
1      33.3        14359          9.0             4.7               2346   
2      31.6         1817          6.6             4.2               1643   
3      38.2        15772          3.6             2.0               2460   
4      33.6         6037          3.8             4.0               3756   
...     ...          ...          ...             ...                ...   
99995  33.1         4726          3.9             2.0               3118   
99996  35.1        11554          4.5             3.1               1967   
99997  18.9         3924          3.8             1.0               2328   
99998  27.8        16110          5.6             0.8               3093   
99999  35.4         8222          9.1             1.8               3942   

       smoker  alcohol  resting_hr  systolic_bp  diastolic_bp  cholesterol  \
0           0        0          97          161           111          240   
1           0        1          68          116            65          207   
2           0        1          90          123            99          296   
3           0        0          71          165            95          175   
4           0        1          98          139            61          294   
...       ...      ...         ...          ...           ...          ...   
99995       0        1          56          105            76          282   
99996       0        0          51          149            77          192   
99997       0        0          69           92           117          218   
99998       0        0          93          164            72          188   
99999       0        1          71          145            80          276   

       family_history  disease_risk  
0                   0             0  
1                   0             0  
2                   0             0  
3                   0             0  
4                   0             0  
...               ...           ...  
99995               0             0  
99996               0             0  
99997               0             0  
99998               0             0  
99999               0             1  

[100000 rows x 13 columns]

In [42]:
df.isna().sum()

bmi                  0
daily_steps          0
sleep_hours          0
water_intake_l       0
calories_consumed    0
smoker               0
alcohol              0
resting_hr           0
systolic_bp          0
diastolic_bp         0
cholesterol          0
family_history       0
disease_risk         0
dtype: int64

In [43]:
df.columns 

Index(['bmi', 'daily_steps', 'sleep_hours', 'water_intake_l',
       'calories_consumed', 'smoker', 'alcohol', 'resting_hr', 'systolic_bp',
       'diastolic_bp', 'cholesterol', 'family_history', 'disease_risk'],
      dtype='object')

In [44]:
X = df.iloc[:,:-1]
Y = df.iloc[:,-1]
X
Y

0        0
1        0
2        0
3        0
4        0
        ..
99995    0
99996    0
99997    0
99998    0
99999    1
Name: disease_risk, Length: 100000, dtype: int64

In [45]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size= 0.3)

X_train
X_test
Y_train
Y_test

14091    0
76882    1
8605     1
39908    0
35677    0
        ..
93038    0
11333    1
99608    0
48198    0
75571    0
Name: disease_risk, Length: 30000, dtype: int64

In [46]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler() 
scaler.fit(X_train) 

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)



In [47]:
X_train

array([[ 0.81528195,  0.94112848, -1.2827695 , ..., -1.18126776,
        -0.72229372,  1.52799297],
       [ 0.610774  ,  1.61866613, -1.62853062, ...,  0.77947663,
         0.71025831, -0.65445327],
       [-1.43430548, -0.74860992, -0.98640283, ..., -0.89292299,
        -1.53099245, -0.65445327],
       ...,
       [ 1.35014889, -0.35445927,  1.53271386, ...,  0.60646977,
        -0.69918805, -0.65445327],
       [ 0.94113299,  0.74405316, -0.73943061, ..., -0.89292299,
        -1.71583787, -0.65445327],
       [-1.05675235,  0.06304844,  1.08816386, ..., -1.35427461,
        -0.39881423,  1.52799297]], shape=(70000, 12))

In [48]:
X_test

array([[ 0.62650538,  0.06724542, -0.14669727, ...,  0.95248349,
        -1.09198457,  1.52799297],
       [ 0.06017568, -1.3971337 ,  0.93998052, ...,  1.1831593 ,
        -0.23707449, -0.65445327],
       [-0.94663268,  0.79970869,  1.28574164, ..., -0.77758509,
        -0.60676533,  1.52799297],
       ...,
       [-1.68600757, -1.53399156, -0.09730282, ..., -0.95059195,
         0.64094127, -0.65445327],
       [ 0.86247609,  0.33749407, -0.04790838, ...,  1.41383511,
         1.05684348,  1.52799297],
       [ 0.97259575, -0.12015862,  1.73029164, ...,  0.72180768,
         0.40988449,  1.52799297]], shape=(30000, 12))

In [49]:
Y_test

14091    0
76882    1
8605     1
39908    0
35677    0
        ..
93038    0
11333    1
99608    0
48198    0
75571    0
Name: disease_risk, Length: 30000, dtype: int64

In [50]:
from sklearn.neighbors import KNeighborsClassifier   

knn = KNeighborsClassifier()   

knn = knn.fit(X_train,Y_train)     

y_pred = knn.predict(X_test)     

y_pred

array([0, 0, 0, ..., 0, 0, 0], shape=(30000,))

In [51]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_pred,Y_test))

0.7032333333333334


In [52]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(Y_test,y_pred)

cm 

array([[20325,  2208],
       [ 6695,   772]])