In [2]:
import pandas
import numpy

In [3]:
data = pandas.read_csv('diabetes.csv')
df = pandas.DataFrame(data)
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [4]:
# target >>>>> outcome
# input features >>> Pregnancies	Glucose	BloodPressure	SkinThickness	Insulin	BMI	DiabetesPedigreeFunction	Age

In [5]:
df.columns    # all columns needed

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [6]:
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [7]:
# after there is no missing value 

# next step :  spliting the data into training(70%) and test(30%)

# scikit-learn

# separating input features and target

# x contains input features and y contains target

In [8]:
X = df.iloc[:,:-1]
Y = df.iloc[:,-1]
X

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [9]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size= 0.3)

X_train
X_test
Y_train
Y_test

209    1
751    0
563    0
122    0
721    0
      ..
491    0
717    0
716    1
305    0
530    0
Name: Outcome, Length: 231, dtype: int64

# after the splitting the next step is scaling

# scaling          
# -------
getting every values in the dataframe to a similar range is called scaling

there are two type scaling : 

# <----standard scaler---->

Z = (X - mean) / standard deviation

Z = resulted scaled value

x = input from training data

mean = mean of the column where x has been taken

standard deviation = std of the column

# <----min max scaler----->

In [10]:
from sklearn.preprocessing import StandardScaler

# we have to create an object for standard deviation

scaler = StandardScaler() 
                                # y_test and y_train already in the range 0 - 1

scaler.fit(X_train)             # only the x_train need to fit here values taken ...so if x_test taken data leakage will happens
                                # here data taken find mean and standard deviation
X_train = scaler.transform(X_train)  # here scaling to a range(like 0 - 1)

X_test = scaler.transform(X_test)  # to avoid the data leakage we put X_test into transform directly

In [11]:
X_train

array([[-1.16200872, -0.69114265, -3.36671483, ..., -0.83353358,
        -0.63014557, -0.95932259],
       [-0.28231133,  2.02582242,  0.06704929, ...,  0.57836035,
        -0.15553927,  0.18510572],
       [ 0.01092113,  1.06870972,  0.31231816, ...,  2.05217946,
        -0.67607522, -0.14187379],
       ...,
       [-1.16200872, -1.67912995,  0.36137193, ...,  1.68062842,
        -0.81080217,  1.00255452],
       [-0.28231133,  0.26597004, -0.22727335, ..., -1.06884923,
        -0.44336503, -0.95932259],
       [-1.16200872,  0.60559068, -3.36671483, ...,  1.32146242,
        -0.77712043, -0.38710843]], shape=(537, 8))

In [12]:
X_test

array([[ 0.89061853,  1.93319861,  0.75380211, ...,  0.46689504,
        -0.317824  ,  0.59383012],
       [-0.86877626, -0.01190138,  0.45947948, ...,  0.90037125,
        -0.60564977, -0.46885331],
       [ 0.59738606, -0.69114265, -0.42348844, ..., -0.59821792,
         0.11697661, -0.14187379],
       ...,
       [-0.28231133,  1.59357798,  0.45947948, ...,  0.25634946,
         1.56529135, -0.22361867],
       [-0.57554379, -0.04277599,  0.36137193, ...,  0.98706649,
        -0.74650067, -0.38710843],
       [-0.57554379,  0.01897322, -0.42348844, ..., -0.23905192,
         0.79061137, -0.95932259]], shape=(231, 8))

In [13]:
Y_test

209    1
751    0
563    0
122    0
721    0
      ..
491    0
717    0
716    1
305    0
530    0
Name: Outcome, Length: 231, dtype: int64

In [14]:
from sklearn.neighbors import KNeighborsClassifier   # KNN class

knn = KNeighborsClassifier()    # k = 5  odd number 5 7 

knn = knn.fit(X_train,Y_train)      #  train hte model using the 70% input features and 70% result
#here knn is the model

y_pred = knn.predict(X_test)        # predict the result for the unseen data(x_test)
#30% input , 30% output

y_pred

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0])

In [15]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_pred,Y_test))

0.7186147186147186


In [16]:
# model performance evaluating methods

# accuracy_score
#================
' accuracy = correct predictions / total predictions'

# recall
#=========
''

# f1_score
#=========
'mean of precision and recall'

# precision
#==========
'out of all predicted result how many are correct'


# supervised learning  >>> classification
# confusion matrix     >>> TruePositive TrueNegative FalsePositive FalseNegative

'out of all predicted result how many are correct'

In [17]:
# TruePositive 
# 0      0
# TrueNegative 
# 1      1
# FalsePositive
# 1      0
#  FalseNegative
# 0      1

"""
[TP  FP 
 FN  TN]
"""

'\n[TP  FP \n FN  TN]\n'

In [18]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(Y_test,y_pred)

cm      #TruePositive - 128 TrueNegative - 22  FalsePositive - 39 FalseNegative - 42

array([[130,  27],
       [ 38,  36]])