In [2]:
# create a array of 3 row and 3 columns
import numpy

In [3]:
numbers = [[1,2,3],[4,5,6],[7,8,9]]
result = numpy.array(numbers)
result

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(result[1,2])
print(result[-1])
print(result[-1,-1])
print(result[:,-1])    # to get column only
print(result[-1,1])
print(result[2,-1])

6
[7 8 9]
9
[3 6 9]
8
9


In [12]:
# slicing
print(result[0:2])    # start:stop  0 to 1
print(result[:,1::])

[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]
 [8 9]]


select last two row
select first two column

In [14]:
print(result[1::])
print(result[:,0:2])

[[4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]


In [ ]:
numbers = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
n = numpy.array(numbers)
n

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [20]:
print(n[0:2,2::])
print(n[0:3,1:3])
print(n[2::,1::])

[[3 4]
 [7 8]]
[[ 2  3]
 [ 6  7]
 [10 11]]
[[10 11 12]
 [14 15 16]]


In [ ]:
# functions
#==========

print(n.mean())
print(n.min())
print(n.max())
print(n.dtype)
print(n.shape)
print(n.ndim)   # showing the dimension of array
# n.reshape(3,2)

8.5
1
16
int64
(4, 4)
2


create a 4,4 matrix

print first row
print first row
print first two row and first three columns using slicing
sum of all elements
min and max of the array
avg of all elements
sum of first row
sum of last column
sum of last two rows
create a new array with each elements multiplied by 2

In [4]:
numbers = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
m = numpy.array(numbers)
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
print(m[0])  # print first row
print(m[:,-1]) # print first row


[1 2 3 4]
[ 4  8 12 16]


In [ ]:
print(m[0:2,0:3]) # print first two row and first three columns using slicing
print(m.sum())    # sum of all elements
print(m.min())    # min and max of the array
print(m.max())
print(m.mean())   # avg of all elements



[[1 2 3]
 [5 6 7]]
136
1
16
8.5


In [ ]:
s = m[0]  # sum of first row
print(s.sum())

10


In [ ]:
s = m[:,-1] # sum of last column
print(s.sum())

40


In [ ]:
s = m[2::] # sum of last two rows
print(s.sum())

100


In [ ]:
s = m * 2 # create a new array with each elements multiplied by 2
s

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])